site_name: QPPTE
theme:
  name: material
  logo:
    images/typewriter.png
  features:
    - navigation.sections

# Markdown extensions
markdown_extensions:
  - attr_list
  - toc:
      permalink: true
  - pymdownx.highlight
  - pymdownx.superfences

nav:
  - "Introduction": "index.md"
  - "Embedding editor": "embedding.md"
  - "Extending editor": "extending.md"